---
- project:
    templates:
      - check-requirements
      - fibostack-python3-antelope-jobs
      - fsc-tox-unit-tips
      - publish-fibostack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - fsc-functional-devstack:
            required-projects:
              - fibostack/python-fibostackclient
        - fsc-functional-devstack-tips:
            voting: false
            # The functional-tips job only tests the latest and shouldn't be run
            # on the stable branches
            branches: ^(?!stable)
            required-projects:
              - fibostack/python-fibostackclient
    gate:
      jobs:
        - fsc-functional-devstack:
            required-projects:
              - fibostack/python-fibostackclient
